services:
  db:
    image: postgres:14
    container_name: techhive_db
    restart: always

    environment:
      POSTGRES_DB: techhive_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: techhive_backend

    command: python manage.py runserver 0.0.0.0:8000

    depends_on:
      - db

    environment:
      DB_NAME: techhive_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432

      DJANGO_ALLOWED_HOSTS: .techhive-ec.com,localhost,127.0.0.1

      DJANGO_CSRF_TRUSTED_ORIGINS: https://*.techhive-ec.com,http://localhost

    expose:
      - "8000"

  frontend:
    build: ./frontend
    container_name: techhive_frontend

    depends_on:
      - backend

    expose:
      - "5173"

  proxy:
    image: caddy:2
    container_name: techhive_proxy
    restart: always

    entrypoint: sh

    command:
      - -c
      - |
        cat > /etc/caddy/Caddyfile <<'EOF'
        techhive-ec.com, *.techhive-ec.com {
            encode gzip

            handle_path /api/* {
                reverse_proxy backend:8000
            }

            handle {
                reverse_proxy frontend:5173
            }
        }
        EOF

        caddy run --config /etc/caddy/Caddyfile --adapter caddyfile

    ports:
      - "80:80"
      - "443:443"

    depends_on:
      - frontend
      - backend

volumes:
  postgres_data: