# Generated by Django 6.0.2 on 2026-03-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario_pub', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario público')),
                ('precio_unitario_emp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio unitario empresa')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor final')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('deuna', 'DeUna'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('otro', 'Otro')], default='efectivo', max_length=20)),
                ('es_feriado', models.BooleanField(default=False)),
                ('es_fin_de_semana', models.BooleanField(default=False)),
                ('mes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dia_semana', models.PositiveSmallIntegerField(blank=True, help_text='0=Lunes, 6=Domingo', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas_venta',
                'ordering': ['-fecha_venta'],
            },
        ),
    ]
